### ISSUE TITLE
TODO: Externalise .ovpn path definition

### ISSUE THREAD

**Issue by andy-nai** [andyn922/docker-openvpn-proxy#5]
I should have the ability to define the ovpn path as a volume instead of defining as a variable. 

This makes the container much easier to use:
1. You can store ovpn file anywhere.
2. You can change config more easily.

**Comment by alturismo** [comment]
Hi, i currently use your docker with another provider then pia, so i had to check where files are ...

currently i mount like this the external ovpn files

-v '/mnt/user/appdata/OpenVPN/pia/':'/app/ovpn/config/pia':'rw'

may a side question, possible to add own DNS Nameserver ?

**Comment by timdonovanuk** [comment]
I thought I'd finally found a working proxy container than lol'ed when I see openvpn configs are hard coded into this. Facepalm.

Edit: got it going with some forking around with volumes. Thanks @andyn922  and @alturismo
